
[env:esp32-c3]
platform = espressif32
board = lolin_c3_mini
board_build.mcu = esp32c3
framework = arduino
board_build.f_cpu = 80000000L
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags = 
    -D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    ; MQTT
    knolleary/PubSubClient @ ^2.8.0
    ; JSON
    bblanchon/ArduinoJson  @ ^7.0.0
    ; Web-интерфейс настроек (подтягивает GyverHTTP, GyverDB, GTL и др. автоматически)
    gyverlibs/Settings       @ ^1.3.0
    GyverLibs/StringUtils
	GyverLibs/Pairs
	GyverLibs/GSON
	GyverLibs/Settings
    ; WebSocket для live-обновлений в вебморде (SettingsGyverWS требует его)
    links2004/WebSockets     @ ^2.4.0
    ; Асинхронное подключение к WiFi + AP fallback
    gyverlibs/WiFiConnector  @ ^1.0.0
    ; ToF дальномер VL53L1X
    pololu/VL53L1X           @ ^1.0.1

